### ISSUE TITLE
Xps file from MemoryStream

### ISSUE THREAD

**Issue by sekulicb** [lzabik/pdfsharp.dotnet.core#1]
Hi. First example from [https://nathanpjones.com/2013/03/output-to-pdf-in-wpf-for-free/](nathanpjones) shows conversion from memory stream. Why is first scenario not supported ?

**Comment by sekulicb** [comment]
I closed this because the library doesn't even work. If you have List box with images in it, it will repeat same image for each row when converting to PDF.

**Comment by lzabik** [comment]
Hello.

The library is a simple port (conversion) of http://pdfsharp.net/ to dotNet Core. I could not find such version so I prepared one and shared it.  According to http://www.nathanpjones.com/wp/2013/03/output-to-pdf-in-wpf-for-free/ there were some problems with the lib.
